// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `userpost.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.user.post;

public interface Userpost extends Ice.Object,
                                  _UserpostOperations, _UserpostOperationsNC
{
    public static final String ice_staticId = "::user::post::Userpost";

    public static final long serialVersionUID = -1293846371L;
}
