default:
  OperateTimeout: 2
  ConnectTimeout: 2
  MessageMaxSize: 65535
  DefaultClientSize: 20
  WarnClientSize: 30
  MaxClientSize: 100
  Compress: true
  Balance: 1
  MonitorPort: 5018
  Heartbeat: 3
  RetryCount: 3

servers:
  - HelloIce:
      MaxClientSize: 100
      WarnClientSize: 30
      Address: 127.0.0.1:1888
      DefaultClientSize : 50
  - ArticleIce:
      MessageMaxSize: 200
      ConnectTimeout: 2
      Address: localhost:1888