version: '3'
services:
  GoiceIce:
    image: aloxc/goicesrv
    ports:
      - 1888:1888
    network_mode: bridge

  UserPostIce:
    image: aloxc/userpostsrv
    ports:
      - 1889:1889
    network_mode: bridge

  goiceclient:
    image: aloxc/goice
    environment:
      - IN_DOCKER : true
    depends_on:
      - GoiceIce
      - UserPostIce
    network_mode: bridge
    links:
      - GoiceIce: GoiceIce
      - UserPostIce: UserPostIce