version: '3'
services:
  goiceclient:
    image: aloxc/goice
    depends_on:
      - goicesrv
      - userpostsrv

  goicesrv:
    image: aloxc/goicesrv
    command: -t
    ports:
      - 1888:1888

  userpostsrv:
    image: aloxc/userpostsrv
    command: -t
    ports:
      - 1889:1889
