version: '3'
services:
  GoiceIce:
    image: aloxc/goicesrv
    container_name: gosrv
    deploy:
      replicas: 3
    ports:
      - 1888:1888

  UserPostIce:
    image: aloxc/userpostsrv
    container_name: usersrv
    ports:
      - 1889:1889

  goiceclient:
    image: aloxc/goiceclient
    container_name: goiceclient
    environment:
      IN_DOCKER: y
    deploy:
      delay: 5s
    depends_on:
      - GoiceIce
      - UserPostIce
    links:
      - GoiceIce:GoiceIce
      - UserPostIce:UserPostIce
