version: '3'
services:
  GoiceIce:
    image: aloxc/goicesrv
    ports:
      - 1888:1888

  UserPostIce:
    image: aloxc/userpostsrv
    ports:
      - 1889:1889

  goiceclient:
    image: aloxc/goice
    environment:
      IN_DOCKER: y
    depends_on:
      - GoiceIce
      - UserPostIce
    volumes:
      - /golang/gopath/src/github.com/aloxc/goice/:/root/goice/
    links:
      - GoiceIce:GoiceIce
      - UserPostIce:UserPostIce
