//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `userpost.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.user.post;

/** @hidden */
public class _UserpostPrxI extends com.zeroc.Ice._ObjectPrxI implements UserpostPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
