default:
  OperateTimeout: 2
  ConnectTimeout: 200
  MaxIdleTime: 300
  MessageMaxSize: 65535
  DefaultClientSize: 20
  WarnClientSize: 30
  MaxClientSize: 100
  Compress: true
  Balance: 1
  MonitorPort: 0
  Heartbeat: 3
  RetryCount: 3

servers:
  - Goice:
      MaxClientSize: 500
      WarnClientSize: 30
      Address: 127.0.0.1:1888
      DefaultClientSize : 500
      Module: goiceinter
      Name: Goice
      IdentityName: Goice
  - UserPostIce:
      MessageMaxSize: 200
      ConnectTimeout: 2
      Address: localhost:1888
      Module: user::post
      Name: Userpost
      IdentityName: UserPost