//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `Goice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.goiceinter;

/** @hidden */
public class _GoicePrxI extends com.zeroc.Ice._ObjectPrxI implements GoicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
