//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `Goice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.goiceinter;

public class Request implements Cloneable,
                                java.io.Serializable
{
    public String method;

    public java.util.Map<String, String> params;

    public Request()
    {
        this.method = "";
    }

    public Request(String method, java.util.Map<String, String> params)
    {
        this.method = method;
        this.params = params;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Request r = null;
        if(rhs instanceof Request)
        {
            r = (Request)rhs;
        }

        if(r != null)
        {
            if(this.method != r.method)
            {
                if(this.method == null || r.method == null || !this.method.equals(r.method))
                {
                    return false;
                }
            }
            if(this.params != r.params)
            {
                if(this.params == null || r.params == null || !this.params.equals(r.params))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::goiceinter::Request");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, method);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, params);
        return h_;
    }

    public Request clone()
    {
        Request c = null;
        try
        {
            c = (Request)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.method);
        ParamsHelper.write(ostr, this.params);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.method = istr.readString();
        this.params = ParamsHelper.read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Request v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Request ice_read(com.zeroc.Ice.InputStream istr)
    {
        Request v = new Request();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Request> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Request v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Request> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Request.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Request _nullMarshalValue = new Request();

    /** @hidden */
    public static final long serialVersionUID = -909069766L;
}
