// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `goice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.goiceinter;

public interface Goice extends Ice.Object,
                               _GoiceOperations, _GoiceOperationsNC
{
    public static final String ice_staticId = "::goiceinter::Goice";

    public static final long serialVersionUID = 1240329881L;
}
