// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `userpost.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.user.post;

public interface UserpostPrx extends Ice.ObjectPrx
{
    public String valuestr(String name, String value);

    public String valuestr(String name, String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_valuestr(String name, String value);

    public Ice.AsyncResult begin_valuestr(String name, String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_valuestr(String name, String value, Ice.Callback __cb);

    public Ice.AsyncResult begin_valuestr(String name, String value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_valuestr(String name, String value, Callback_Userpost_valuestr __cb);

    public Ice.AsyncResult begin_valuestr(String name, String value, java.util.Map<String, String> __ctx, Callback_Userpost_valuestr __cb);

    public Ice.AsyncResult begin_valuestr(String name,
                                          String value,
                                          IceInternal.Functional_GenericCallback1<String> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_valuestr(String name,
                                          String value,
                                          IceInternal.Functional_GenericCallback1<String> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_valuestr(String name,
                                          String value,
                                          java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_GenericCallback1<String> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_valuestr(String name,
                                          String value,
                                          java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_GenericCallback1<String> __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public String end_valuestr(Ice.AsyncResult __result);

    public String valuelong(String name, long value);

    public String valuelong(String name, long value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_valuelong(String name, long value);

    public Ice.AsyncResult begin_valuelong(String name, long value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_valuelong(String name, long value, Ice.Callback __cb);

    public Ice.AsyncResult begin_valuelong(String name, long value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_valuelong(String name, long value, Callback_Userpost_valuelong __cb);

    public Ice.AsyncResult begin_valuelong(String name, long value, java.util.Map<String, String> __ctx, Callback_Userpost_valuelong __cb);

    public Ice.AsyncResult begin_valuelong(String name,
                                           long value,
                                           IceInternal.Functional_GenericCallback1<String> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_valuelong(String name,
                                           long value,
                                           IceInternal.Functional_GenericCallback1<String> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_valuelong(String name,
                                           long value,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<String> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_valuelong(String name,
                                           long value,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<String> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public String end_valuelong(Ice.AsyncResult __result);

    public String threeparams(String name, int value, double any);

    public String threeparams(String name, int value, double any, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_threeparams(String name, int value, double any);

    public Ice.AsyncResult begin_threeparams(String name, int value, double any, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_threeparams(String name, int value, double any, Ice.Callback __cb);

    public Ice.AsyncResult begin_threeparams(String name, int value, double any, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_threeparams(String name, int value, double any, Callback_Userpost_threeparams __cb);

    public Ice.AsyncResult begin_threeparams(String name, int value, double any, java.util.Map<String, String> __ctx, Callback_Userpost_threeparams __cb);

    public Ice.AsyncResult begin_threeparams(String name,
                                             int value,
                                             double any,
                                             IceInternal.Functional_GenericCallback1<String> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_threeparams(String name,
                                             int value,
                                             double any,
                                             IceInternal.Functional_GenericCallback1<String> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_threeparams(String name,
                                             int value,
                                             double any,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_GenericCallback1<String> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_threeparams(String name,
                                             int value,
                                             double any,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_GenericCallback1<String> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public String end_threeparams(Ice.AsyncResult __result);

    public String doarr(String[] sar, int[] iarr, String key, String value, int i);

    public String doarr(String[] sar, int[] iarr, String key, String value, int i, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_doarr(String[] sar, int[] iarr, String key, String value, int i);

    public Ice.AsyncResult begin_doarr(String[] sar, int[] iarr, String key, String value, int i, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_doarr(String[] sar, int[] iarr, String key, String value, int i, Ice.Callback __cb);

    public Ice.AsyncResult begin_doarr(String[] sar, int[] iarr, String key, String value, int i, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_doarr(String[] sar, int[] iarr, String key, String value, int i, Callback_Userpost_doarr __cb);

    public Ice.AsyncResult begin_doarr(String[] sar, int[] iarr, String key, String value, int i, java.util.Map<String, String> __ctx, Callback_Userpost_doarr __cb);

    public Ice.AsyncResult begin_doarr(String[] sar,
                                       int[] iarr,
                                       String key,
                                       String value,
                                       int i,
                                       IceInternal.Functional_GenericCallback1<String> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_doarr(String[] sar,
                                       int[] iarr,
                                       String key,
                                       String value,
                                       int i,
                                       IceInternal.Functional_GenericCallback1<String> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_doarr(String[] sar,
                                       int[] iarr,
                                       String key,
                                       String value,
                                       int i,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_GenericCallback1<String> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_doarr(String[] sar,
                                       int[] iarr,
                                       String key,
                                       String value,
                                       int i,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_GenericCallback1<String> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public String end_doarr(Ice.AsyncResult __result);

    public String todo(String json);

    public String todo(String json, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_todo(String json);

    public Ice.AsyncResult begin_todo(String json, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_todo(String json, Ice.Callback __cb);

    public Ice.AsyncResult begin_todo(String json, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_todo(String json, Callback_Userpost_todo __cb);

    public Ice.AsyncResult begin_todo(String json, java.util.Map<String, String> __ctx, Callback_Userpost_todo __cb);

    public Ice.AsyncResult begin_todo(String json,
                                      IceInternal.Functional_GenericCallback1<String> __responseCb,
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_todo(String json,
                                      IceInternal.Functional_GenericCallback1<String> __responseCb,
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_todo(String json,
                                      java.util.Map<String, String> __ctx,
                                      IceInternal.Functional_GenericCallback1<String> __responseCb,
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_todo(String json,
                                      java.util.Map<String, String> __ctx,
                                      IceInternal.Functional_GenericCallback1<String> __responseCb,
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                      IceInternal.Functional_BoolCallback __sentCb);

    public String end_todo(Ice.AsyncResult __result);

    public int[] getIntArr(int i);

    public int[] getIntArr(int i, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIntArr(int i);

    public Ice.AsyncResult begin_getIntArr(int i, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIntArr(int i, Ice.Callback __cb);

    public Ice.AsyncResult begin_getIntArr(int i, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getIntArr(int i, Callback_Userpost_getIntArr __cb);

    public Ice.AsyncResult begin_getIntArr(int i, java.util.Map<String, String> __ctx, Callback_Userpost_getIntArr __cb);

    public Ice.AsyncResult begin_getIntArr(int i,
                                           IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getIntArr(int i,
                                           IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getIntArr(int i,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getIntArr(int i,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public int[] end_getIntArr(Ice.AsyncResult __result);

    public String[] getStrArr(int i);

    public String[] getStrArr(int i, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStrArr(int i);

    public Ice.AsyncResult begin_getStrArr(int i, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStrArr(int i, Ice.Callback __cb);

    public Ice.AsyncResult begin_getStrArr(int i, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getStrArr(int i, Callback_Userpost_getStrArr __cb);

    public Ice.AsyncResult begin_getStrArr(int i, java.util.Map<String, String> __ctx, Callback_Userpost_getStrArr __cb);

    public Ice.AsyncResult begin_getStrArr(int i,
                                           IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getStrArr(int i,
                                           IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getStrArr(int i,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getStrArr(int i,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public String[] end_getStrArr(Ice.AsyncResult __result);
}
