// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `goice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.goiceinter;

public interface _GoiceOperationsNC
{
    String non();

    String getString();

    String getStringFrom(String value);

    String[] getStringArr();

    String[] getStringArrFrom(String[] arr);

    String two(String from, String to);

    void vvoid();

    void vvoidTo(String value);

    byte getByte();

    byte getByteFrom(byte value);

    byte[] getByteArr();

    byte[] getByteArrFrom(byte[] arr);

    boolean getBool();

    boolean getBoolFrom(boolean value);

    boolean[] getBoolArr();

    boolean[] getBoolArrFrom(boolean[] arr);

    short getShort();

    short getShortFrom(short value);

    short[] getShortArr();

    short[] getShortArrFrom(short[] arr);

    int getInt();

    int getIntFrom(int value);

    int[] getIntArr();

    int[] getIntArrFrom(int[] arr);

    long getLong();

    long getLongFrom(long value);

    long[] getLongArr();

    long[] getLongArrFrom(long[] arr);

    float getFloat();

    float getFloatFrom(float value);

    float[] getFloatArr();

    float[] getFloatArrFrom(float[] arr);

    double getDouble();

    double getDoubleFrom(double value);

    double[] getDoubleArr();

    double[] getDoubleArrFrom(double[] arr);

    String execute(Request request);
}
