// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `goice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.goiceinter;

public abstract class Callback_Goice_getDouble
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackDouble
{
    public final void __completed(Ice.AsyncResult __result)
    {
        GoicePrxHelper.__getDouble_completed(this, __result);
    }
}
