// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `goice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.goiceinter;

public interface GoicePrx extends Ice.ObjectPrx
{
    public String non();

    public String non(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_non();

    public Ice.AsyncResult begin_non(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_non(Ice.Callback __cb);

    public Ice.AsyncResult begin_non(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_non(Callback_Goice_non __cb);

    public Ice.AsyncResult begin_non(java.util.Map<String, String> __ctx, Callback_Goice_non __cb);

    public Ice.AsyncResult begin_non(IceInternal.Functional_GenericCallback1<String> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_non(IceInternal.Functional_GenericCallback1<String> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_non(java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_GenericCallback1<String> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_non(java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_GenericCallback1<String> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public String end_non(Ice.AsyncResult __result);

    public String getString();

    public String getString(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getString();

    public Ice.AsyncResult begin_getString(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getString(Ice.Callback __cb);

    public Ice.AsyncResult begin_getString(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getString(Callback_Goice_getString __cb);

    public Ice.AsyncResult begin_getString(java.util.Map<String, String> __ctx, Callback_Goice_getString __cb);

    public Ice.AsyncResult begin_getString(IceInternal.Functional_GenericCallback1<String> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getString(IceInternal.Functional_GenericCallback1<String> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getString(java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<String> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getString(java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<String> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public String end_getString(Ice.AsyncResult __result);

    public String getStringFrom(String value);

    public String getStringFrom(String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStringFrom(String value);

    public Ice.AsyncResult begin_getStringFrom(String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStringFrom(String value, Ice.Callback __cb);

    public Ice.AsyncResult begin_getStringFrom(String value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getStringFrom(String value, Callback_Goice_getStringFrom __cb);

    public Ice.AsyncResult begin_getStringFrom(String value, java.util.Map<String, String> __ctx, Callback_Goice_getStringFrom __cb);

    public Ice.AsyncResult begin_getStringFrom(String value,
                                               IceInternal.Functional_GenericCallback1<String> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getStringFrom(String value,
                                               IceInternal.Functional_GenericCallback1<String> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getStringFrom(String value,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_GenericCallback1<String> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getStringFrom(String value,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_GenericCallback1<String> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public String end_getStringFrom(Ice.AsyncResult __result);

    public String[] getStringArr();

    public String[] getStringArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStringArr();

    public Ice.AsyncResult begin_getStringArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStringArr(Ice.Callback __cb);

    public Ice.AsyncResult begin_getStringArr(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getStringArr(Callback_Goice_getStringArr __cb);

    public Ice.AsyncResult begin_getStringArr(java.util.Map<String, String> __ctx, Callback_Goice_getStringArr __cb);

    public Ice.AsyncResult begin_getStringArr(IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getStringArr(IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getStringArr(java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getStringArr(java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public String[] end_getStringArr(Ice.AsyncResult __result);

    public String[] getStringArrFrom(String[] arr);

    public String[] getStringArrFrom(String[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr, Ice.Callback __cb);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr, Callback_Goice_getStringArrFrom __cb);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr, java.util.Map<String, String> __ctx, Callback_Goice_getStringArrFrom __cb);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr,
                                                  IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr,
                                                  IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr,
                                                  java.util.Map<String, String> __ctx,
                                                  IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getStringArrFrom(String[] arr,
                                                  java.util.Map<String, String> __ctx,
                                                  IceInternal.Functional_GenericCallback1<String[]> __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public String[] end_getStringArrFrom(Ice.AsyncResult __result);

    public String two(String from, String to);

    public String two(String from, String to, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_two(String from, String to);

    public Ice.AsyncResult begin_two(String from, String to, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_two(String from, String to, Ice.Callback __cb);

    public Ice.AsyncResult begin_two(String from, String to, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_two(String from, String to, Callback_Goice_two __cb);

    public Ice.AsyncResult begin_two(String from, String to, java.util.Map<String, String> __ctx, Callback_Goice_two __cb);

    public Ice.AsyncResult begin_two(String from,
                                     String to,
                                     IceInternal.Functional_GenericCallback1<String> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_two(String from,
                                     String to,
                                     IceInternal.Functional_GenericCallback1<String> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_two(String from,
                                     String to,
                                     java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_GenericCallback1<String> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_two(String from,
                                     String to,
                                     java.util.Map<String, String> __ctx,
                                     IceInternal.Functional_GenericCallback1<String> __responseCb,
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                     IceInternal.Functional_BoolCallback __sentCb);

    public String end_two(Ice.AsyncResult __result);

    public void vvoid();

    public void vvoid(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_vvoid();

    public Ice.AsyncResult begin_vvoid(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_vvoid(Ice.Callback __cb);

    public Ice.AsyncResult begin_vvoid(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_vvoid(Callback_Goice_vvoid __cb);

    public Ice.AsyncResult begin_vvoid(java.util.Map<String, String> __ctx, Callback_Goice_vvoid __cb);

    public Ice.AsyncResult begin_vvoid(IceInternal.Functional_VoidCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_vvoid(IceInternal.Functional_VoidCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_vvoid(java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_VoidCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_vvoid(java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_VoidCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_vvoid(Ice.AsyncResult __result);

    public void vvoidTo(String value);

    public void vvoidTo(String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_vvoidTo(String value);

    public Ice.AsyncResult begin_vvoidTo(String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_vvoidTo(String value, Ice.Callback __cb);

    public Ice.AsyncResult begin_vvoidTo(String value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_vvoidTo(String value, Callback_Goice_vvoidTo __cb);

    public Ice.AsyncResult begin_vvoidTo(String value, java.util.Map<String, String> __ctx, Callback_Goice_vvoidTo __cb);

    public Ice.AsyncResult begin_vvoidTo(String value,
                                         IceInternal.Functional_VoidCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_vvoidTo(String value,
                                         IceInternal.Functional_VoidCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_vvoidTo(String value,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_VoidCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_vvoidTo(String value,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_VoidCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_vvoidTo(Ice.AsyncResult __result);

    public byte getByte();

    public byte getByte(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getByte();

    public Ice.AsyncResult begin_getByte(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getByte(Ice.Callback __cb);

    public Ice.AsyncResult begin_getByte(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getByte(Callback_Goice_getByte __cb);

    public Ice.AsyncResult begin_getByte(java.util.Map<String, String> __ctx, Callback_Goice_getByte __cb);

    public Ice.AsyncResult begin_getByte(IceInternal.Functional_ByteCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getByte(IceInternal.Functional_ByteCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getByte(java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_ByteCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getByte(java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_ByteCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public byte end_getByte(Ice.AsyncResult __result);

    public byte getByteFrom(byte value);

    public byte getByteFrom(byte value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getByteFrom(byte value);

    public Ice.AsyncResult begin_getByteFrom(byte value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getByteFrom(byte value, Ice.Callback __cb);

    public Ice.AsyncResult begin_getByteFrom(byte value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getByteFrom(byte value, Callback_Goice_getByteFrom __cb);

    public Ice.AsyncResult begin_getByteFrom(byte value, java.util.Map<String, String> __ctx, Callback_Goice_getByteFrom __cb);

    public Ice.AsyncResult begin_getByteFrom(byte value,
                                             IceInternal.Functional_ByteCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getByteFrom(byte value,
                                             IceInternal.Functional_ByteCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getByteFrom(byte value,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_ByteCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getByteFrom(byte value,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_ByteCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public byte end_getByteFrom(Ice.AsyncResult __result);

    public byte[] getByteArr();

    public byte[] getByteArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getByteArr();

    public Ice.AsyncResult begin_getByteArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getByteArr(Ice.Callback __cb);

    public Ice.AsyncResult begin_getByteArr(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getByteArr(Callback_Goice_getByteArr __cb);

    public Ice.AsyncResult begin_getByteArr(java.util.Map<String, String> __ctx, Callback_Goice_getByteArr __cb);

    public Ice.AsyncResult begin_getByteArr(IceInternal.Functional_GenericCallback1<byte[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getByteArr(IceInternal.Functional_GenericCallback1<byte[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getByteArr(java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<byte[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getByteArr(java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<byte[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public byte[] end_getByteArr(Ice.AsyncResult __result);

    public byte[] getByteArrFrom(byte[] arr);

    public byte[] getByteArrFrom(byte[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr, Ice.Callback __cb);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr, Callback_Goice_getByteArrFrom __cb);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr, java.util.Map<String, String> __ctx, Callback_Goice_getByteArrFrom __cb);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr,
                                                IceInternal.Functional_GenericCallback1<byte[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr,
                                                IceInternal.Functional_GenericCallback1<byte[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr,
                                                java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_GenericCallback1<byte[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getByteArrFrom(byte[] arr,
                                                java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_GenericCallback1<byte[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    public byte[] end_getByteArrFrom(Ice.AsyncResult __result);

    public boolean getBool();

    public boolean getBool(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBool();

    public Ice.AsyncResult begin_getBool(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBool(Ice.Callback __cb);

    public Ice.AsyncResult begin_getBool(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBool(Callback_Goice_getBool __cb);

    public Ice.AsyncResult begin_getBool(java.util.Map<String, String> __ctx, Callback_Goice_getBool __cb);

    public Ice.AsyncResult begin_getBool(IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBool(IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getBool(java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBool(java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_getBool(Ice.AsyncResult __result);

    public boolean getBoolFrom(boolean value);

    public boolean getBoolFrom(boolean value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBoolFrom(boolean value);

    public Ice.AsyncResult begin_getBoolFrom(boolean value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBoolFrom(boolean value, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBoolFrom(boolean value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBoolFrom(boolean value, Callback_Goice_getBoolFrom __cb);

    public Ice.AsyncResult begin_getBoolFrom(boolean value, java.util.Map<String, String> __ctx, Callback_Goice_getBoolFrom __cb);

    public Ice.AsyncResult begin_getBoolFrom(boolean value,
                                             IceInternal.Functional_BoolCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBoolFrom(boolean value,
                                             IceInternal.Functional_BoolCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getBoolFrom(boolean value,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_BoolCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBoolFrom(boolean value,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_BoolCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_getBoolFrom(Ice.AsyncResult __result);

    public boolean[] getBoolArr();

    public boolean[] getBoolArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBoolArr();

    public Ice.AsyncResult begin_getBoolArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBoolArr(Ice.Callback __cb);

    public Ice.AsyncResult begin_getBoolArr(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBoolArr(Callback_Goice_getBoolArr __cb);

    public Ice.AsyncResult begin_getBoolArr(java.util.Map<String, String> __ctx, Callback_Goice_getBoolArr __cb);

    public Ice.AsyncResult begin_getBoolArr(IceInternal.Functional_GenericCallback1<boolean[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBoolArr(IceInternal.Functional_GenericCallback1<boolean[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getBoolArr(java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<boolean[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBoolArr(java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<boolean[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public boolean[] end_getBoolArr(Ice.AsyncResult __result);

    public boolean[] getBoolArrFrom(boolean[] arr);

    public boolean[] getBoolArrFrom(boolean[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr, Callback_Goice_getBoolArrFrom __cb);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr, java.util.Map<String, String> __ctx, Callback_Goice_getBoolArrFrom __cb);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr,
                                                IceInternal.Functional_GenericCallback1<boolean[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr,
                                                IceInternal.Functional_GenericCallback1<boolean[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr,
                                                java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_GenericCallback1<boolean[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getBoolArrFrom(boolean[] arr,
                                                java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_GenericCallback1<boolean[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    public boolean[] end_getBoolArrFrom(Ice.AsyncResult __result);

    public short getShort();

    public short getShort(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getShort();

    public Ice.AsyncResult begin_getShort(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getShort(Ice.Callback __cb);

    public Ice.AsyncResult begin_getShort(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getShort(Callback_Goice_getShort __cb);

    public Ice.AsyncResult begin_getShort(java.util.Map<String, String> __ctx, Callback_Goice_getShort __cb);

    public Ice.AsyncResult begin_getShort(IceInternal.Functional_ShortCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getShort(IceInternal.Functional_ShortCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getShort(java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_ShortCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getShort(java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_ShortCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public short end_getShort(Ice.AsyncResult __result);

    public short getShortFrom(short value);

    public short getShortFrom(short value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getShortFrom(short value);

    public Ice.AsyncResult begin_getShortFrom(short value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getShortFrom(short value, Ice.Callback __cb);

    public Ice.AsyncResult begin_getShortFrom(short value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getShortFrom(short value, Callback_Goice_getShortFrom __cb);

    public Ice.AsyncResult begin_getShortFrom(short value, java.util.Map<String, String> __ctx, Callback_Goice_getShortFrom __cb);

    public Ice.AsyncResult begin_getShortFrom(short value,
                                              IceInternal.Functional_ShortCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getShortFrom(short value,
                                              IceInternal.Functional_ShortCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getShortFrom(short value,
                                              java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_ShortCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getShortFrom(short value,
                                              java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_ShortCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public short end_getShortFrom(Ice.AsyncResult __result);

    public short[] getShortArr();

    public short[] getShortArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getShortArr();

    public Ice.AsyncResult begin_getShortArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getShortArr(Ice.Callback __cb);

    public Ice.AsyncResult begin_getShortArr(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getShortArr(Callback_Goice_getShortArr __cb);

    public Ice.AsyncResult begin_getShortArr(java.util.Map<String, String> __ctx, Callback_Goice_getShortArr __cb);

    public Ice.AsyncResult begin_getShortArr(IceInternal.Functional_GenericCallback1<short[]> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getShortArr(IceInternal.Functional_GenericCallback1<short[]> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getShortArr(java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_GenericCallback1<short[]> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getShortArr(java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_GenericCallback1<short[]> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public short[] end_getShortArr(Ice.AsyncResult __result);

    public short[] getShortArrFrom(short[] arr);

    public short[] getShortArrFrom(short[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr, Ice.Callback __cb);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr, Callback_Goice_getShortArrFrom __cb);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr, java.util.Map<String, String> __ctx, Callback_Goice_getShortArrFrom __cb);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr,
                                                 IceInternal.Functional_GenericCallback1<short[]> __responseCb,
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr,
                                                 IceInternal.Functional_GenericCallback1<short[]> __responseCb,
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr,
                                                 java.util.Map<String, String> __ctx,
                                                 IceInternal.Functional_GenericCallback1<short[]> __responseCb,
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getShortArrFrom(short[] arr,
                                                 java.util.Map<String, String> __ctx,
                                                 IceInternal.Functional_GenericCallback1<short[]> __responseCb,
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public short[] end_getShortArrFrom(Ice.AsyncResult __result);

    public int getInt();

    public int getInt(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getInt();

    public Ice.AsyncResult begin_getInt(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getInt(Ice.Callback __cb);

    public Ice.AsyncResult begin_getInt(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getInt(Callback_Goice_getInt __cb);

    public Ice.AsyncResult begin_getInt(java.util.Map<String, String> __ctx, Callback_Goice_getInt __cb);

    public Ice.AsyncResult begin_getInt(IceInternal.Functional_IntCallback __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getInt(IceInternal.Functional_IntCallback __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getInt(java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_IntCallback __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getInt(java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_IntCallback __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                        IceInternal.Functional_BoolCallback __sentCb);

    public int end_getInt(Ice.AsyncResult __result);

    public int getIntFrom(int value);

    public int getIntFrom(int value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIntFrom(int value);

    public Ice.AsyncResult begin_getIntFrom(int value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIntFrom(int value, Ice.Callback __cb);

    public Ice.AsyncResult begin_getIntFrom(int value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getIntFrom(int value, Callback_Goice_getIntFrom __cb);

    public Ice.AsyncResult begin_getIntFrom(int value, java.util.Map<String, String> __ctx, Callback_Goice_getIntFrom __cb);

    public Ice.AsyncResult begin_getIntFrom(int value,
                                            IceInternal.Functional_IntCallback __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getIntFrom(int value,
                                            IceInternal.Functional_IntCallback __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getIntFrom(int value,
                                            java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_IntCallback __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getIntFrom(int value,
                                            java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_IntCallback __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public int end_getIntFrom(Ice.AsyncResult __result);

    public int[] getIntArr();

    public int[] getIntArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIntArr();

    public Ice.AsyncResult begin_getIntArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIntArr(Ice.Callback __cb);

    public Ice.AsyncResult begin_getIntArr(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getIntArr(Callback_Goice_getIntArr __cb);

    public Ice.AsyncResult begin_getIntArr(java.util.Map<String, String> __ctx, Callback_Goice_getIntArr __cb);

    public Ice.AsyncResult begin_getIntArr(IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getIntArr(IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getIntArr(java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getIntArr(java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public int[] end_getIntArr(Ice.AsyncResult __result);

    public int[] getIntArrFrom(int[] arr);

    public int[] getIntArrFrom(int[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr, Ice.Callback __cb);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr, Callback_Goice_getIntArrFrom __cb);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr, java.util.Map<String, String> __ctx, Callback_Goice_getIntArrFrom __cb);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr,
                                               IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr,
                                               IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getIntArrFrom(int[] arr,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_GenericCallback1<int[]> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public int[] end_getIntArrFrom(Ice.AsyncResult __result);

    public long getLong();

    public long getLong(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLong();

    public Ice.AsyncResult begin_getLong(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLong(Ice.Callback __cb);

    public Ice.AsyncResult begin_getLong(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLong(Callback_Goice_getLong __cb);

    public Ice.AsyncResult begin_getLong(java.util.Map<String, String> __ctx, Callback_Goice_getLong __cb);

    public Ice.AsyncResult begin_getLong(IceInternal.Functional_LongCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLong(IceInternal.Functional_LongCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getLong(java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_LongCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLong(java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_LongCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public long end_getLong(Ice.AsyncResult __result);

    public long getLongFrom(long value);

    public long getLongFrom(long value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLongFrom(long value);

    public Ice.AsyncResult begin_getLongFrom(long value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLongFrom(long value, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLongFrom(long value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLongFrom(long value, Callback_Goice_getLongFrom __cb);

    public Ice.AsyncResult begin_getLongFrom(long value, java.util.Map<String, String> __ctx, Callback_Goice_getLongFrom __cb);

    public Ice.AsyncResult begin_getLongFrom(long value,
                                             IceInternal.Functional_LongCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLongFrom(long value,
                                             IceInternal.Functional_LongCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getLongFrom(long value,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_LongCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLongFrom(long value,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_LongCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public long end_getLongFrom(Ice.AsyncResult __result);

    public long[] getLongArr();

    public long[] getLongArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLongArr();

    public Ice.AsyncResult begin_getLongArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLongArr(Ice.Callback __cb);

    public Ice.AsyncResult begin_getLongArr(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLongArr(Callback_Goice_getLongArr __cb);

    public Ice.AsyncResult begin_getLongArr(java.util.Map<String, String> __ctx, Callback_Goice_getLongArr __cb);

    public Ice.AsyncResult begin_getLongArr(IceInternal.Functional_GenericCallback1<long[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLongArr(IceInternal.Functional_GenericCallback1<long[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getLongArr(java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<long[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLongArr(java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<long[]> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public long[] end_getLongArr(Ice.AsyncResult __result);

    public long[] getLongArrFrom(long[] arr);

    public long[] getLongArrFrom(long[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr, Callback_Goice_getLongArrFrom __cb);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr, java.util.Map<String, String> __ctx, Callback_Goice_getLongArrFrom __cb);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr,
                                                IceInternal.Functional_GenericCallback1<long[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr,
                                                IceInternal.Functional_GenericCallback1<long[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr,
                                                java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_GenericCallback1<long[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLongArrFrom(long[] arr,
                                                java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_GenericCallback1<long[]> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    public long[] end_getLongArrFrom(Ice.AsyncResult __result);

    public float getFloat();

    public float getFloat(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFloat();

    public Ice.AsyncResult begin_getFloat(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFloat(Ice.Callback __cb);

    public Ice.AsyncResult begin_getFloat(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFloat(Callback_Goice_getFloat __cb);

    public Ice.AsyncResult begin_getFloat(java.util.Map<String, String> __ctx, Callback_Goice_getFloat __cb);

    public Ice.AsyncResult begin_getFloat(IceInternal.Functional_FloatCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getFloat(IceInternal.Functional_FloatCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getFloat(java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_FloatCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getFloat(java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_FloatCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public float end_getFloat(Ice.AsyncResult __result);

    public float getFloatFrom(float value);

    public float getFloatFrom(float value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFloatFrom(float value);

    public Ice.AsyncResult begin_getFloatFrom(float value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFloatFrom(float value, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFloatFrom(float value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFloatFrom(float value, Callback_Goice_getFloatFrom __cb);

    public Ice.AsyncResult begin_getFloatFrom(float value, java.util.Map<String, String> __ctx, Callback_Goice_getFloatFrom __cb);

    public Ice.AsyncResult begin_getFloatFrom(float value,
                                              IceInternal.Functional_FloatCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getFloatFrom(float value,
                                              IceInternal.Functional_FloatCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getFloatFrom(float value,
                                              java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_FloatCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getFloatFrom(float value,
                                              java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_FloatCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public float end_getFloatFrom(Ice.AsyncResult __result);

    public float[] getFloatArr();

    public float[] getFloatArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFloatArr();

    public Ice.AsyncResult begin_getFloatArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFloatArr(Ice.Callback __cb);

    public Ice.AsyncResult begin_getFloatArr(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFloatArr(Callback_Goice_getFloatArr __cb);

    public Ice.AsyncResult begin_getFloatArr(java.util.Map<String, String> __ctx, Callback_Goice_getFloatArr __cb);

    public Ice.AsyncResult begin_getFloatArr(IceInternal.Functional_GenericCallback1<float[]> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getFloatArr(IceInternal.Functional_GenericCallback1<float[]> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getFloatArr(java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_GenericCallback1<float[]> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getFloatArr(java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_GenericCallback1<float[]> __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public float[] end_getFloatArr(Ice.AsyncResult __result);

    public float[] getFloatArrFrom(float[] arr);

    public float[] getFloatArrFrom(float[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr, Callback_Goice_getFloatArrFrom __cb);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr, java.util.Map<String, String> __ctx, Callback_Goice_getFloatArrFrom __cb);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr,
                                                 IceInternal.Functional_GenericCallback1<float[]> __responseCb,
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr,
                                                 IceInternal.Functional_GenericCallback1<float[]> __responseCb,
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr,
                                                 java.util.Map<String, String> __ctx,
                                                 IceInternal.Functional_GenericCallback1<float[]> __responseCb,
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getFloatArrFrom(float[] arr,
                                                 java.util.Map<String, String> __ctx,
                                                 IceInternal.Functional_GenericCallback1<float[]> __responseCb,
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public float[] end_getFloatArrFrom(Ice.AsyncResult __result);

    public double getDouble();

    public double getDouble(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDouble();

    public Ice.AsyncResult begin_getDouble(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDouble(Ice.Callback __cb);

    public Ice.AsyncResult begin_getDouble(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDouble(Callback_Goice_getDouble __cb);

    public Ice.AsyncResult begin_getDouble(java.util.Map<String, String> __ctx, Callback_Goice_getDouble __cb);

    public Ice.AsyncResult begin_getDouble(IceInternal.Functional_DoubleCallback __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDouble(IceInternal.Functional_DoubleCallback __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getDouble(java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_DoubleCallback __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDouble(java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_DoubleCallback __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public double end_getDouble(Ice.AsyncResult __result);

    public double getDoubleFrom(double value);

    public double getDoubleFrom(double value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDoubleFrom(double value);

    public Ice.AsyncResult begin_getDoubleFrom(double value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDoubleFrom(double value, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDoubleFrom(double value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDoubleFrom(double value, Callback_Goice_getDoubleFrom __cb);

    public Ice.AsyncResult begin_getDoubleFrom(double value, java.util.Map<String, String> __ctx, Callback_Goice_getDoubleFrom __cb);

    public Ice.AsyncResult begin_getDoubleFrom(double value,
                                               IceInternal.Functional_DoubleCallback __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDoubleFrom(double value,
                                               IceInternal.Functional_DoubleCallback __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getDoubleFrom(double value,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_DoubleCallback __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDoubleFrom(double value,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_DoubleCallback __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public double end_getDoubleFrom(Ice.AsyncResult __result);

    public double[] getDoubleArr();

    public double[] getDoubleArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDoubleArr();

    public Ice.AsyncResult begin_getDoubleArr(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDoubleArr(Ice.Callback __cb);

    public Ice.AsyncResult begin_getDoubleArr(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDoubleArr(Callback_Goice_getDoubleArr __cb);

    public Ice.AsyncResult begin_getDoubleArr(java.util.Map<String, String> __ctx, Callback_Goice_getDoubleArr __cb);

    public Ice.AsyncResult begin_getDoubleArr(IceInternal.Functional_GenericCallback1<double[]> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDoubleArr(IceInternal.Functional_GenericCallback1<double[]> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getDoubleArr(java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_GenericCallback1<double[]> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDoubleArr(java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_GenericCallback1<double[]> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public double[] end_getDoubleArr(Ice.AsyncResult __result);

    public double[] getDoubleArrFrom(double[] arr);

    public double[] getDoubleArrFrom(double[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr, Callback_Goice_getDoubleArrFrom __cb);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr, java.util.Map<String, String> __ctx, Callback_Goice_getDoubleArrFrom __cb);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr,
                                                  IceInternal.Functional_GenericCallback1<double[]> __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr,
                                                  IceInternal.Functional_GenericCallback1<double[]> __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr,
                                                  java.util.Map<String, String> __ctx,
                                                  IceInternal.Functional_GenericCallback1<double[]> __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDoubleArrFrom(double[] arr,
                                                  java.util.Map<String, String> __ctx,
                                                  IceInternal.Functional_GenericCallback1<double[]> __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public double[] end_getDoubleArrFrom(Ice.AsyncResult __result);

    public String execute(Request request);

    public String execute(Request request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_execute(Request request);

    public Ice.AsyncResult begin_execute(Request request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_execute(Request request, Ice.Callback __cb);

    public Ice.AsyncResult begin_execute(Request request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_execute(Request request, Callback_Goice_execute __cb);

    public Ice.AsyncResult begin_execute(Request request, java.util.Map<String, String> __ctx, Callback_Goice_execute __cb);

    public Ice.AsyncResult begin_execute(Request request,
                                         IceInternal.Functional_GenericCallback1<String> __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_execute(Request request,
                                         IceInternal.Functional_GenericCallback1<String> __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_execute(Request request,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_GenericCallback1<String> __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_execute(Request request,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_GenericCallback1<String> __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public String end_execute(Ice.AsyncResult __result);
}
