// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `goice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.github.aloxc.goiceinter;

public enum HouseType implements java.io.Serializable
{
    
    Apartment(5),
    
    Villa(6);

    public int
    value()
    {
        return __value;
    }

    public static HouseType
    valueOf(int __v)
    {
        switch(__v)
        {
        case 5:
            return Apartment;
        case 6:
            return Villa;
        }
        return null;
    }

    private
    HouseType(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 6);
    }

    public static void
    __write(IceInternal.BasicStream __os, HouseType __v)
    {
        if(__v == null)
        {
            __os.writeEnum(HouseType.Apartment.value(), 6);
        }
        else
        {
            __os.writeEnum(__v.value(), 6);
        }
    }

    public static HouseType
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(6);
        return __validate(__v);
    }

    private static HouseType
    __validate(int __v)
    {
        final HouseType __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
